### ISSUE TITLE
QR code and Verify Message buttons on File->Receive Addresses menu

### ISSUE THREAD

**Issue by ny2cafuse** [aurarad/Auroracoin#1]
QR code and Verify Message buttons on File->Receive Addresses menu do not WAI.  QR code button should return the popup page that is displayed when you double-click on a receive address in the receive tab.  Verify Message button can be removed, as the File->Verify Message menu option can be used instead.

**Comment by ny2cafuse** [comment]
May or may not be an issue at this time depending on the Qt5 update to the wallet.  Will discuss further with the team to find out if it should be addressed now or just roll it into the next update.

**Comment by BioMike** [comment]
This goes in the next version. I'll have a look into it.

**Comment by BioMike** [comment]
Ok, so... when I copied over the interface from the old wallet, these buttons copied over, but their underlying workings are non-existent in the DGB code base. The QR-code should work from the payment requests of the "receive" screen. I'm not sure if anyone uses the message verification feature, or that we should keep that feature, as it is more of an "advanced" feature (which has more to do with cryptography then sending payments).

So, 2 options:
1) Copy over all the code to implement the features that the buttons should do.
2) Ditch the buttons from that screen. QR-code feature is covered by the payment requests.

**Comment by ny2cafuse** [comment]
I say ditch the buttons.  That or at least redirect the QR link to the the qt qr window from the payment request screen.

**Comment by BioMike** [comment]
Fixed in commit  f1be536. Closing
