### ISSUE TITLE
No Install Dir Prompt

### ISSUE THREAD

**Issue by diveyez** [aurarad/Auroracoin#13]
You really need to allow users to define the install location, and data storage location. This is a GIVEN.

**Comment by BioMike** [comment]
Install location would need an installer (on windows), on *nix systems you could use the prefix variable during configure stage when self building the binaries.

Data storage location can be given with the --datadir variable.

Keeping this bug open for future re-evaluation.

**Comment by BioMike** [comment]
Windows has an installer now. Closing.
