### ISSUE TITLE
Recipe for target failed..

### ISSUE THREAD

**Issue by diveyez** [aurarad/Auroracoin#15]
Makefile:938: recipe for target 'addrman.o' failed
make[3]: *** [addrman.o] Error 1
make[3]: Leaving directory '/media/auroracoin-2017.02.1.0/src'
Makefile:960: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/media/auroracoin-2017.02.1.0/src'
Makefile:680: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/media/auroracoin-2017.02.1.0/src'
Makefile:669: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
diveyez@*********************************:/media/au

**Comment by BioMike** [comment]
This information is not informative. I would need the lines above to know what went wrong. It only says addrman.cpp compilation failed and stopped further compilation. Also, provide information regarding your system. Do note that the master branch does not compile on systems with the newest GCC.

**Comment by leandrogomesmachado** [comment]
https://github.com/reddcoin-project/reddcoin/issues/103

This will solve your problem, just change the numbers to the correct coin! :)

**Comment by BioMike** [comment]
@machado-rev I don't think that bug is related to this. Also the openssl-1.1 support is already handled in bug #12.

**Comment by leandrogomesmachado** [comment]
@BioMike it's related to the edition of chainparams.cpp.

It works with me on my server.

Look this comment:

https://github.com/reddcoin-project/reddcoin/issues/103#issuecomment-357026185

This coin need a rework on network params to be better on syncing too!

Have a nice day,

**Comment by BioMike** [comment]
@machado-rev those changes are already in the development branch.

I agree syncing should be improved, but it should sync within a few hours.

**Comment by leandrogomesmachado** [comment]
Thanks @BioMike 

I have experienced a problem with my server (using dbcache or not) that the node sync like 2k blocks and stop. To keep syncing I had to stop and start the daemon again.

Thank you, have a nice day!

**Comment by BioMike** [comment]
@machado-rev could you try to see if you can reliably replicate it and see if it gets stuck at a specific block? If that is the case please open a new bug for that (not to pollute this bug). If it doesn't get stuck at a specific block, please open a new bug with a title like "Improve initial block syncing.".

**Comment by BioMike** [comment]
New release should sync faster. Closing
