### ISSUE TITLE
auroracoind core dumps on start

### ISSUE THREAD

**Issue by ergofobe** [aurarad/auroracoin#15]
This issue is with the latest commit dd875f52677839ae234703726cdec3986367f4d2. 

After a successful build, starting auroracoind causes a core dump with the following error:

auroracoind: chainparams.cpp:149: CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("0x2a8e100939494904af825b488596ddd536b3a96226ad02e0f7ab7ae472b27a8e")' failed.
Aborted (core dumped)

**Comment by ny2cafuse** [comment]
The commit you're referencing is on a development branch that hasn't been anywhere near finished yet.  When it is completed, tested, and verified working, it will be merged into a master branch and made the main repo.  That's a little ways off though.

If you're trying to build AUR, you need to build from the master-0.8 branch, which is the main branch at this time.
