### ISSUE TITLE
Building with missing flags  ... 

### ISSUE THREAD

**Issue by red0bear** [aurarad/Auroracoin#16]
I tried to compile berkley Db ... but it fails too .... under opensuse 15.0

checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing

**Comment by BioMike** [comment]
If I'm correct opensuse 15.0 provides Berkeley DB 4.8. Auroracoin uses Berkeley DB 5.3.

**Comment by red0bear** [comment]
But when you compile from oracle and you try to point source dir ..... it give fails is same way .....

**Comment by red0bear** [comment]
But when you compile from oracle and you try to point source dir ..... it give fails is same way .....

**Comment by BioMike** [comment]
If I remember correctly, you should point to the build_unix dir, not src (source) dir. Alternatively install it first in a safe prefix (e.g. /home/red0bear/db53) and pass that to configure.

**Comment by red0bear** [comment]
Still have same effect ... from the first time i typed. configure should work any place. There is no build_unix folder too......

**Comment by frndxyz** [comment]
i am instaling it from source and including it in ./configure command. (Linux)

curl -O http://download.oracle.com/berkeley-db/db-5.3.21.tar.gz


tar -xvf db-5.3.21.tar.gz

cd db-5.3.21/build_unix
 mkdir -p build
 BDB_PREFIX=$(pwd)/build
 ../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
 make install

then ...

./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/"

hope this helps.

**Comment by BioMike** [comment]
The new release has a tool to build BerkeleyDB 5.3. Closing
