### ISSUE TITLE
Configure should mention Berkeley DB version. (Was: Build Error)

### ISSUE THREAD

**Issue by vr4dude316** [aurarad/Auroracoin#19]
I keep getting this error when ./configure is run.
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing

i just built a fresh 16.04 box and am still getting this error.  nothing else is installed.  have run...

apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev
apt-get install libboost-all-dev git npm nodejs nodejs-legacy libminiupnpc-dev redis-server
add-apt-repository ppa:bitcoin/bitcoin
apt-get update
apt-get install libdb4.8-dev libdb4.8++-dev
curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh
source ~/.profile
nvm install 0.10.25
nvm use 0.10.25

**Comment by vr4dude316** [comment]
installing this, worked

sudo apt-get install libdb5.3++-dev

**Comment by BioMike** [comment]
Yes, Auroracoin uses Berkeley DB 5.3. I'll change the title to fix the build message to be clearer about the version one needs.

**Comment by BioMike** [comment]
Fixed with commit 8e43aa7. Closing
