### ISSUE TITLE
Web wallet not accebile - how to retrive coins

### ISSUE THREAD

**Issue by serejandmyself** [aurarad/Auroracoin#20]
I have the seed phrase from my web wallet. But I noticed recently, that the web wallet isn't available anymore. How do I gain access to my funds?

**Comment by SkateFish** [comment]
Here is a link on Reddit to help explain the process.   I am working on a better document to walk you through the process.  But see if you can follow this in the meanwhile. 

https://www.reddit.com/r/auroracoin/comments/9bxgsn/unable_to_send_funds_with_auroracoin_webwallet/

**Comment by SkateFish** [comment]
If you have any problems post them here....  We are committed to help you retrieve your coins.

**Comment by serejandmyself** [comment]
Solved. Thank you
