### ISSUE TITLE
Chrome wallet not sending 

### ISSUE THREAD

**Issue by serejandmyself** [aurarad/Auroracoin#22]
Im using the chrome wallet. Strange but i can send coins from any address apart from one. Which is this:
AeTpPSYKDEUkFAnRKnbCRApE1RC78cCr79

Nothing happens. I cant see anything wrong in the console either. 

Is that a known issue? How to solve this?

**Comment by BioMike** [comment]
The Chrome wallet is being maintained by someone else. Please report your problem to https://github.com/SkateFish/auroracoin-browser-wallet

I was notified that recently a new version of that wallet was released, so mention in the report the version you're using.
