### ISSUE TITLE
auroracoin-qt-20180910.exe

### ISSUE THREAD

**Issue by JohPePe** [aurarad/Auroracoin#23]
auroracoin-qt-20180910.exe is infected with a trojan called Win32/CryptInjet
Could one get one clean exe from some other place?

**Comment by BioMike** [comment]
Thank you for reporting. This is very strange as how this got in there, but the sha256 hash was indeed not the same as was initially uploaded. I've reuploaded the binary and confirmed the hash by download again. Should be ok now, if not let me know again.

**Comment by CandleHater** [comment]
> Thank you for reporting. This is very strange as how this got in there, but the sha256 hash was indeed not the same as was initially uploaded. I've reuploaded the binary and confirmed the hash by download again. Should be ok now, if not let me know again.

lol, you didn't. That's what I call a supreme ScamCoin, well done Sir.

**Comment by BioMike** [comment]
> > Thank you for reporting. This is very strange as how this got in there, but the sha256 hash was indeed not the same as was initially uploaded. I've reuploaded the binary and confirmed the hash by download again. Should be ok now, if not let me know again.
> 
> lol, you didn't. That's what I call a supreme ScamCoin, well done Sir.

Not sure what's the issue?

8c8190bf301d747c966157ebdcf16ee85d1a302ee5eecd48bcdab64b2aa56835  auroracoin-qt-20180910.exe <= infected file
f2c355337876ca20bba93b3eda7a31d6b5a89981e2622bd73602f15e6455e98c  auroracoin-qt-20180910.exe <= correct file

Please elaborate what's the problem.

**Comment by CandleHater** [comment]
> f2c355337876ca20bba93b3eda7a31d6b5a89981e2622bd73602f15e6455e98c auroracoin-qt-20180910.exe <= correct file
> 
> Please elaborate what's the problem.

The problem is, that you're still infecting people with malware. The hash of the file you mention as "correct file" is infected: https://www.virustotal.com/gui/file/f2c355337876ca20bba93b3eda7a31d6b5a89981e2622bd73602f15e6455e98c/detection

**Comment by BioMike** [comment]
This is not the virus reported earlier in the OP. Do note that all wallets have a risk of being flagged by anti-virus software as a virus, due to the way these core wallets work. For example, our code contains code to mine the blocks for the algos that we use. That triggers a false positive in some virus scanners, because the virusses use that same code (originally from bitcoin core) to mine on infected computers. This is a known problem and if someone wants to tackle it, we're happy to accept any help.

That having said, looking at the virustotal link you gave, almost all larger/common virus scanner suites don't report anything wrong with the file. Only "microsoft" is the exception and I've seen the same false positive when testing the wallet on a windows machine.

For now, there is little I can do, if there is no additional proof there is something wrong (like the hash being wrong mentioned by the OP).

**Comment by JohPePe** [comment]
Yes, downloaded the file and it installed without any problems. Thanks

Any ideas how to restore old wallet from hive.auroracoin.is?

**Comment by BioMike** [comment]
Hive was run by some other team members, I've send them a notification to answer your question, but they sometimes can take their time to answer. In the worst case you have to setup your own server (or someone else from our team) to transfer your coins out. From what I understood from them at the time they set it up is, that as long as you have your "secret", you're able to regenerate your wallet.

**Comment by frndxyz** [comment]
> Yes, downloaded the file and it installed without any problems. Thanks
> 
> Any ideas how to restore old wallet from hive.auroracoin.is?

Can you try to import hive passphrase to coinomi? I am sure it should work.

**Comment by JohPePe** [comment]
@frndxyz Can't find any way to import passphrase into coinomi, any ideas?
@BioMike Thanks, I've got my passphrase and my pin, hope they can fix it asap. :-)

**Comment by SkateFish** [comment]
@JohPePe 

This is the only way I know of to get coins from your Hive word/pass phrase.

-Download the official Auroracoin chrome extension wallet.
https://chrome.google.com/webstore/detail/auroracoin-browser-wallet/ibbbddhliiimfdpadncmdnbhgagplagk

-Go to https://iancoleman.io/bip39/

Place your Hive Web Wallet 12 word phrase in the BIP39 phrase box
Change Number of Words to 12
Change Coin to Auroracoin Under Derivation Path
Change Tab to Bip32 Tab
Change BIP Derivation Path to m/0'/0
Under Derived Addresses check that the first address is your address in Hive
Copy the Private Key on the right side and Import into the Chrome Extension

***  Note- It is recommended to run the bip39 html on a machine not connected to Internet to get the private keys.   However this site is directly linked from Coinomi and I believe is safe to use.  I simply moved the coins right away to another wallet and then created a new chrome extension wallet.

**Comment by JohPePe** [comment]
@SkateFish Thanks, that solved my problem.
Have a nice evening :-)

**Comment by BioMike** [comment]
Copied that instruction to the github wiki for future reference.

As follow up: I'm in contact with Github to further investigate this. Official statements will follow through our communication channels if/when our team gets relevant information for our users. For now, I don't see the need to keep this issue open.
