### ISSUE TITLE
require "getblockhashes" rpc method for insight explorer.

### ISSUE THREAD

**Issue by frndxyz** [aurarad/Auroracoin#24]
i have setup latest insight explorer for auroracoin here:
http://213.126.73.99:3001/  

it does not fetching blocks because insight api require support for "getblockhashes" rpc method to fetch multiple blocks.

**Comment by BioMike** [comment]
Bitcoin doesn't have this. Which coin introduced this? Could you give a link to the source code?

**Comment by frndxyz** [comment]
Bitpay version of bitcoin has implemented it.

pull request of getblockhashes and some indexes: https://github.com/bitpay/bitcoin/pull/6

**Comment by BioMike** [comment]
Resolved with commit 0e33e48. Closing.
