### ISSUE TITLE
TX inputs does not return address and amount data.

### ISSUE THREAD

**Issue by frndxyz** [aurarad/Auroracoin#25]
in below output "VIN" has "addr", "valueSat" , "value" json field are null.
 
    "txid": "ddf20d2903c5728fd125409a219f3947e9c5b3f3acc063ac970834164004dae6",
    "version": 1,
    "locktime": 0,
    "vin": [
        {
            "txid": "a8b5a1cbea9ad63a91003fe5e0f3c1da763c0a4e9c906cc998dcf175471b3610",
            "vout": 1,
            "sequence": 4294967295,
            "n": 0,
            "scriptSig": {
                "hex": "48304502205bb5196e1685de639379d1a8c5693c959b6203912b1b70232e42e904999a4ddd022100ac8bdbb800568f3daef0a6128d626b2e042fb30ac8f63dc5f0863a73a356eddb012103d2eb55a7c64ebfabed8d32851b1108eda65bcf9403523dc749800c77af19c5f8",
                "asm": "304502205bb5196e1685de639379d1a8c5693c959b6203912b1b70232e42e904999a4ddd022100ac8bdbb800568f3daef0a6128d626b2e042fb30ac8f63dc5f0863a73a356eddb[ALL] 03d2eb55a7c64ebfabed8d32851b1108eda65bcf9403523dc749800c77af19c5f8"
            },
            "addr": null,
            "valueSat": null,
            "value": null,
            "doubleSpentTxID": null
        },
        {
            "txid": "d72a44dcba8648100f20ad1e612f41f1786a2722fd3f7bd594c061c42d36cc75",
            "vout": 1,
            "sequence": 4294967295,
            "n": 1,
            "scriptSig": {
                "hex": "4830450220638d91fd008addead7341683e855560d3d28b0f5a2c79c3681a7f0b43b2c3e12022100f0822bb7e2a4fe1f1e802e6c1050ba3671bccc3a23937733da2b00964f3edffa0121024aefd74c474dcb62c06f379fc8f19be03dc2bb8dd3dc08fc7f20ba6a047442b3",
                "asm": "30450220638d91fd008addead7341683e855560d3d28b0f5a2c79c3681a7f0b43b2c3e12022100f0822bb7e2a4fe1f1e802e6c1050ba3671bccc3a23937733da2b00964f3edffa[ALL] 024aefd74c474dcb62c06f379fc8f19be03dc2bb8dd3dc08fc7f20ba6a047442b3"
            },
            "addr": null,
            "valueSat": null,
            "value": null,
            "doubleSpentTxID": null
        },
        {
            "txid": "5e715b11fcdcfbc26a4b01f943a6b8caebcc2d1fb20c0452a82ff1ba46cabd9f",
            "vout": 0,
            "sequence": 4294967295,
            "n": 2,
            "scriptSig": {
                "hex": "47304402201a1b4a9faabb3aa338eb3815d5beaa5ce25dd5822709910f0286e4c9ea58d9ce02201b8ecba28150e479fa9d690ff4c613e9abcdedbb76e6222c6ff08e82d6b379d0012103a834eb115826f8edaf79dc14315bcf16c4240baab8d7fe2398e37f6eb0b19f8e",
                "asm": "304402201a1b4a9faabb3aa338eb3815d5beaa5ce25dd5822709910f0286e4c9ea58d9ce02201b8ecba28150e479fa9d690ff4c613e9abcdedbb76e6222c6ff08e82d6b379d0[ALL] 03a834eb115826f8edaf79dc14315bcf16c4240baab8d7fe2398e37f6eb0b19f8e"
            },
            "addr": null,
            "valueSat": null,
            "value": null,
            "doubleSpentTxID": null
        },
        {
            "txid": "a3044a2bbe55f01d2f368565b5d1d48c56339798d4e4c9d185f469121dd074a0",
            "vout": 1,
            "sequence": 4294967295,
            "n": 3,
            "scriptSig": {
                "hex": "48304502207dc06393bbbe8326f3cb1d583b87ef3441a16a4bede48c5ec74d5bc53f8b970b022100808554cd8697781943e2ef9d8252df97a75d84d0bf5d21859c1797ae4618e60a012103c36c41c91b06fcccb94602f2dd4f701c0cd0daee701713940ac40e75cbe70b52",
                "asm": "304502207dc06393bbbe8326f3cb1d583b87ef3441a16a4bede48c5ec74d5bc53f8b970b022100808554cd8697781943e2ef9d8252df97a75d84d0bf5d21859c1797ae4618e60a[ALL] 03c36c41c91b06fcccb94602f2dd4f701c0cd0daee701713940ac40e75cbe70b52"
            },
            "addr": null,
            "valueSat": null,
            "value": null,
            "doubleSpentTxID": null
        }
    ],
    "vout": [
        {
            "value": "0.01036863",
            "n": 0,
            "scriptPubKey": {
                "hex": "76a914ee0c3ad0f1dd86ce4ac2f410a6d4703e4dab4f2b88ac",
                "asm": "OP_DUP OP_HASH160 ee0c3ad0f1dd86ce4ac2f410a6d4703e4dab4f2b OP_EQUALVERIFY OP_CHECKSIG",
                "addresses": [
                    "AdUZ7tgm2NGDsBEseHGgfCAcCerxuDbCXB"
                ],
                "type": "pubkeyhash"
            },
            "spentTxId": null,
            "spentIndex": null,
            "spentHeight": null
        },
        {
            "value": "15.53054182",
            "n": 1,
            "scriptPubKey": {
                "hex": "76a914072634af7aefcab03542e3d652dd8c64c494502a88ac",
                "asm": "OP_DUP OP_HASH160 072634af7aefcab03542e3d652dd8c64c494502a OP_EQUALVERIFY OP_CHECKSIG",
                "addresses": [
                    "AGRg9RiA5YTnBDL6XD37CmRCvpL1SiA7DS"
                ],
                "type": "pubkeyhash"
            },
            "spentTxId": null,
            "spentIndex": null,
            "spentHeight": null
        }
    ],
    "blockhash": "0beb5667d997b1b54af8b9fe7a54a7f6890713a20394d567fd4471aa5fbafdef",
    "blockheight": -1,
    "confirmations": 0,
    "time": 1395271386,
    "valueOut": 15.54091045,
    "size": 669,
    "valueIn": null,
    "fees": null
}

from google i found some patches made by DASH team might be helpful.

https://github.com/dashpay/dash/pull/1839
https://github.com/dashpay/dash/issues/1767

**Comment by BioMike** [comment]
Could you give the rpc command that returns this?

**Comment by frndxyz** [comment]
> Could you give the rpc command that returns this?

This response is from insight explorer. But actual command from auroracoin daemon is:

Auroracoin-cli Getrawtransaction tx 1

I found this  issue with insight explorer and not auroracoin. Bitcoin raw tx return same result. But somehow insight missing code to identify different tx and parse it.

**Comment by frndxyz** [comment]
https://github.com/bitpay/bitcoin/blob/d28f8866845da6e6b893fd2d0b95342e39819e02/src/rpcrawtransaction.cpp#L62

https://github.com/bitpay/bitcoin/blob/0.12.1-bitcore/src/rpcrawtransaction.cpp#L62


it looks like bitpay version of bitcoin-core has implemented address and amount data for inputs.

**Comment by BioMike** [comment]
So to get this right, insight hasn't got specific code to handle vanilla bitcoin core? Insight uses the bitpay version on their explorer?

**Comment by frndxyz** [comment]
> So to get this right, insight hasn't got specific code to handle vanilla bitcoin core? Insight uses the bitpay version on their explorer?

Yes , specially newer version of insight .

**Comment by BioMike** [comment]
Resolved with commit 0e33e48. Closing.
