### ISSUE TITLE
Linux compile fails

### ISSUE THREAD

**Issue by ultra-pool** [aurarad/Auroracoin#28]
` CXX      wallet/libauroracoin_wallet_a-walletutil.o

wallet/walletutil.cpp: In function ‘std::vector<boost::filesystem::path> ListWalletDir()’:

wallet/walletutil.cpp:62:32: error: ‘relative’ is not a member of ‘fs’

             paths.emplace_back(fs::relative(it->path(), wallet_dir));

                                ^
wallet/walletutil.cpp:73:36: error: ‘relative’ is not a member of ‘fs’

                 paths.emplace_back(fs::relative(it->path(), wallet_dir));

                                    ^
Makefile:7371: recipe for target 'wallet/libauroracoin_wallet_a-walletutil.o' failed

make[2]: *** [wallet/libauroracoin_wallet_a-walletutil.o] Error 1

make[2]: Leaving directory '/home/c/Auroracoin12_29_2019/src'

Makefile:10723: recipe for target 'all-recursive' failed

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory '/home/c/Auroracoin12_29_2019/src'

Makefile:777: recipe for target 'all-recursive' failed

make: *** [all-recursive] Error 1`

**Comment by BioMike** [comment]
What Boost version are you using? fs::relative (which is a namespace for boost::filesystem::relative) was introduced in Boost 1.60.0.

**Comment by ultra-pool** [comment]
Got it working. Had to commit out lines 62 and 73 in /src/wallet/walletutil.cpp
Buddy of mine got it working with using that.
