### ISSUE TITLE
boost 1.69 compat

### ISSUE THREAD

**Issue by lvypaul** [aurarad/Auroracoin#30]
compile failure with boost 1.69

rpcserver.cpp: At global scope:
rpcserver.cpp:431:115: error: wrong number of template arguments (2, should be 1)
  431 | static void RPCAcceptHandler(boost::shared_ptr< boost::asio::basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
      |                                                                                                                   ^
In file included from /usr/include/boost/asio.hpp:30,
                 from rpcprotocol.h:15,
                 from rpcserver.h:10,
                 from rpcserver.cpp:6:
/usr/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: provided for ‘template<class Protocol> class boost::asio::basic_socket_acceptor’
   73 | class basic_socket_acceptor
      |       ^~~~~~~~~~~~~~~~~~~~~
rpcserver.cpp:431:117: error: template argument 1 is invalid
  431 | static void RPCAcceptHandler(boost::shared_ptr< boost::asio::basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
      |                                                                                                                     ^
rpcserver.cpp:441:108: error: wrong number of template arguments (2, should be 1)
  441 | static void RPCListen(boost::shared_ptr< boost::asio::basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
      |                                                                                                            ^
In file included from /usr/include/boost/asio.hpp:30,
                 from rpcprotocol.h:15,
                 from rpcserver.h:10,
                 from rpcserver.cpp:6:
/usr/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: provided for ‘template<class Protocol> class boost::asio::basic_socket_acceptor’
   73 | class basic_socket_acceptor
      |       ^~~~~~~~~~~~~~~~~~~~~
......

**Comment by lvypaul** [comment]
easy solution, just deleted the , SocketAcceptorService where I found it, 
It compiled further, hope it works :)

**Comment by lvypaul** [comment]
on another machine failed at:
rpcclient.cpp: In function ‘json_spirit::Object CallRPC(const string&, const Array&)’:
rpcclient.cpp:37:84: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
   37 |     boost::asio::ssl::context context(io_service, boost::asio::ssl::context::sslv23);
      |                                                                                    ^
In file included from /usr/include/boost/asio/ssl/context.hpp:757,
                 from /usr/include/boost/asio/ssl.hpp:18,
                 from rpcprotocol.h:16,
                 from rpcclient.cpp:8:
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note: candidate: ‘boost::asio::ssl::context::context(boost::asio::ssl::context&&)’
  371 | context::context(context&& other)
      | ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note: candidate: ‘boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)’
   63 | context::context(context::method m)

found fix by deleting "io_service" from arguments on line 37

Also, please, when you finish the preparation for compilation please write a warning in the last lines when the compilation is done without GUI. I had to read all the lines to understand that i was missing libprotobuf and that is why my gui wallet was not created

**Comment by BioMike** [comment]
Which branch is this? Master of Stable?

**Comment by lvypaul** [comment]
Stable, built on Fedora core 31 and 32 with boost v1.69 
I think I had another error after these but I do not remember now what was that.  it think something with .impl I had to change it to .native_handle

Anyway, wallet is working and looks stable.

**Comment by BioMike** [comment]
Stable is old and this is a known issue with it. I'm working on a new release, which I hope to have finished soon.

**Comment by BioMike** [comment]
New release is out that should fix this problem. Closing.
