### ISSUE TITLE
Language Localization

### ISSUE THREAD

**Issue by SkateFish** [aurarad/Auroracoin#33]
Open Issue for discussing localization support.

**Comment by SkateFish** [comment]
I assume the main focus now is on https://github.com/aurarad/Auroracoin/blob/master/src/qt/locale/auroracoin_is.ts

**Comment by BioMike** [comment]
Yes, needs to be updated for the new version. I'm also currently working on the Dutch one. I think this is one of the last few things before releasing a new version.

**Comment by BioMike** [comment]
New release has been done. Changes to localizations can be done through PRs. Closing.
