### ISSUE TITLE
Using auroracoin-qt windows, request payment Bech32

### ISSUE THREAD

**Issue by SkateFish** [aurarad/Auroracoin#34]
Requesting Bech32 address gives a Digibyte Bech32 address and URI.

**Comment by BioMike** [comment]
Bech32 addresses aren't supported at the moment. Support is in the new/upcoming wallet code, but should not be accessible. What are you doing to get this? Any suggestions on transforming it into an Auroracoin-specific Bech32 address/URI?

**Comment by SkateFish** [comment]
Dont have any suggestions yet regarding AUR bech32...   but i found this on the Win64 QT Wallet interface, request payment.

**Comment by BioMike** [comment]
Thank you for spotting this: commit 7f6fd71 resolves this issue for now and commit b969cf7 removes the Digibyte HRP part of the Bech32 address and replaces it for an Auroracoin version.

**Comment by BioMike** [comment]
AUR bech32 addresses have been masked in the new release. Will be fully implemented in a future release. Closing
