### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by jjj092353** [aurarad/Auroracoin#4]
config.status: creating src/bitcoin-config.h
config.status: executing depfiles commands
root@pools:/home/coins/Auroracoin# make
Making all in src
make[1]: Entering directory `/home/coins/Auroracoin/src'
make  all-recursive
make[2]: Entering directory`/home/coins/Auroracoin/src'
Making all in .
make[3]: Entering directory `/home/coins/Auroracoin/src'
  CXX      addrman.o
  CXX      alert.o
  CXX      bloom.o
  CXX      checkpoints.o
  CXX      coins.o
  CXX      init.o
  CXX      keystore.o
  CXX      leveldbwrapper.o
  CXX      main.o
  CXX      miner.o
  CXX      net.o
net.cpp:1090:6: error: #error "Must have miniupnp version >= 1.6"
     #error "Must have miniupnp version >= 1.6"
      ^
net.cpp: In function âvoid ThreadMapPort()â:
net.cpp:1076:18: warning: unused variable âmulticastifâ [-Wunused-variable]
     const char * multicastif = 0;
                  ^
net.cpp:1077:18: warning: unused variable âminissdpdpathâ [-Wunused-variable]
     const char * minissdpdpath = 0;
                  ^
make[3]: *** [net.o] Error 1
make[3]: Leaving directory`/home/coins/Auroracoin/src'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/home/coins/Auroracoin/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/home/coins/Auroracoin/src'
make: **\* [all-recursive] Error 1
root@pools:/home/coins/Auroracoin# ls -l

**Comment by ny2cafuse** [comment]
If your version of libminiupnpc-dev isn't 1.6 or higher, you'll need to update your version or compile without UPnP.  Instructions for both options can be found here: 

https://github.com/aurarad/Auroracoin/blob/master/doc/build-unix.md

Follow up on this issue if you're still having issues with it.
