### ISSUE TITLE
DNS Seeders returning only one IP,  and always the same one

### ISSUE THREAD

**Issue by dbkeys** [aurarad/Auroracoin#53]
Expected Behavior:
A properly set up DNS Seeder / Node Tracker will build a database of many node IP's and when queried from DNS will return several IP's.

**Actual behavior**
Only a single IP is being returned when querying the DNS seeders, and always the same one per seeder. This indicate something is wrong.

**To reproduce**
Use the `dig` tool to query DNS servers:
dig electrum1.auroracoin.is A     // 'A' for IPv4, and *always* returns 94.242.229.111
dig electrum2.auroracoin.is A    //   always returns 104.236.13.120
dig electrum3.auroracoin.is A    //   always returns 178.62.202.79
dig electrum4.auroracoin.is A    //   always returns 178.62.5.211

This is a problem, because all wallets / nodes are then trying to connect to these 4 other IP's nodes, and will likely exceed the available connections. 

For comparison, try this:
dig dnsseed.auroracoin.cc A

;; ANSWER SECTION:     // 8 different IP's returned, with one call
dnsseed.auroracoin.cc.	3600	IN	A	62.171.189.219
dnsseed.auroracoin.cc.	3600	IN	A	85.15.179.171
dnsseed.auroracoin.cc.	3600	IN	A	157.161.128.56
dnsseed.auroracoin.cc.	3600	IN	A	147.135.191.162
dnsseed.auroracoin.cc.	3600	IN	A	65.109.141.173
dnsseed.auroracoin.cc.	3600	IN	A	80.65.23.139
dnsseed.auroracoin.cc.	3600	IN	A	87.98.244.13
dnsseed.auroracoin.cc.	3600	IN	A	66.151.242.154

dig dnsseed.auroracoin.cc A           // repeat the call, get 8 IP's , but slightly different set now, as it should be
;; ANSWER SECTION:
dnsseed.auroracoin.cc.	3600	IN	A	85.15.179.171
dnsseed.auroracoin.cc.	3600	IN	A	147.135.191.162
dnsseed.auroracoin.cc.	3600	IN	A	141.95.146.47
dnsseed.auroracoin.cc.	3600	IN	A	5.188.104.245
dnsseed.auroracoin.cc.	3600	IN	A	87.98.244.13
dnsseed.auroracoin.cc.	3600	IN	A	62.171.189.219
dnsseed.auroracoin.cc.	3600	IN	A	91.206.16.214
dnsseed.auroracoin.cc.	3600	IN	A	83.221.211.116

**Comment by dbkeys** [comment]
Fixing this might very likely also alleviate or fix Issue #48

**Comment by BioMike** [comment]
Merged the PR, closing.
