### ISSUE TITLE
Compiling Auroracoin from 'depends' folder fails

### ISSUE THREAD

**Issue by dbkeys** [aurarad/Auroracoin#54]
Compiling Auroracoin in the 'depends' folder results in 
failure, because of dependency stored in a defunct website:
Fetching boost_1_70_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.70.0/source/
curl: (22) The requested URL returned error: 404

(website has ceased operations: 	https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

depends folder should be self-sufficient: contain all the source neccessary to build the program

**Comment by BioMike** [comment]
Fixed with commit 0d80ab4821001f58ca104cc35f8482bfb2ba6e62. Closing.

**Comment by dbkeys** [comment]
Thank you, dnsseed.auroracoin.cc running well.
Best,
DBKeys

Bitmark - The Original Marking BlockChain CryptoCurrency - https://bitmark.io

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
