### ISSUE TITLE
Update compile documentation.

### ISSUE THREAD

**Issue by ny2cafuse** [aurarad/Auroracoin#8]
Update compile documentation to include release changes to prerequisites.

**Comment by ny2cafuse** [comment]
Resolved with 89b6e88aa1b2deecd3f54b310a4945c8be142237

**Comment by BioMike** [comment]
Reopening, as I was not finished with this yet. Large parts still need to be rewritten.

**Comment by BioMike** [comment]
Compile documentation for MacOSX and WIndows are good enough. Closing
